version: '3.9'


services:
  cyclone:
    image: 'webmakom/cyclone:0.0.10'
    restart: always
#    ports:
#      - "3231:3231" # http api
#      - "3203:3203" # p2p
    environment:
      CYCLONE_LABEL: 'local.1'
      CYCLONE_PEERS: '164.68.127.226:3203,164.68.127.58:3203'
    depends_on:
      - storage
      - vm
      - crypto
    network_mode: 'host'

  vm:
    image: 'webmakom/vm:0.0.8'
    restart: always
#    ports:
#      - "8039:8039" # http api
    depends_on:
      - storage
    network_mode: 'host'

  gw:
    image: 'webmakom/gw:0.0.7'
    restart: always
#    ports:
#      - "9231:9231" # http api
    depends_on:
      - storage
      - crypto
    network_mode: 'host'

  crypto:
    image: 'webmakom/crypto:0.0.2'
    restart: always
#    ports:
#      - "3305:3305" # http api
    network_mode: 'host'

  storage:
    image: 'webmakom/storage:0.0.4'
#    ports:
#      - 8801:8801
#      - 8802:8802
    depends_on:
      - mongo-db
    network_mode: 'host'

  mongo-db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    network_mode: 'host'
#    ports:
#      - 27017:27017

volumes:
  mongo_data: {}