version: '3.9'

networks:
  sai:
    name: 'sai'

services:
  cyclone:
    image: 'webmakom/cyclone:0.0.4'
    restart: always
    ports:
      - "3231:3231" # http api
      - "3203:3203" # p2p
    environment:
      CYCLONE_LABEL: 'p3'
      CYCLONE_PEERS: '164.68.127.67:3203,164.68.127.226:3203'
      CYCLONE_PK: 'L4Ssf73vMkw1LLBwKghkw7MoT1MMuLmzhZLLJhnNZPC4PnBWT3K8'
      CYCLONE_PUB: '02f0e0b631078574a0064d92ac449d4e4ef70b8f213f3c05fab109e4f017dba0ad'
      CYCLONE_ADDR: '1L3cxnDxCYUuyzHgu9N4cexR7zeSEoLJvo'
    depends_on:
      - storage
      - vm
      - crypto
    networks:
      - sai

  vm:
    image: 'webmakom/vm:0.0.4'
    restart: always
    ports:
      - "8039:8039" # http api
    depends_on:
      - storage
    networks:
      - sai

  gw:
    image: 'webmakom/gw:0.0.4'
    restart: always
    ports:
      - "9231:9231" # http api
    depends_on:
      - storage
      - crypto
    networks:
      - sai

  crypto:
    image: 'webmakom/crypto:0.0.1'
    restart: always
    ports:
      - "3305:3305" # http api
    networks:
      - sai

  storage:
    image: 'webmakom/storage:0.0.2'
    ports:
      - 8801:8801
      - 8802:8802
    depends_on:
      - mongo-db
    networks:
      - sai

  mongo-db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - sai
    ports:
      - 27018:27017

volumes:
  mongo_data: {}