version: '3.9'


networks:
  boba:
    name: 'boba'
    internal: false
    driver: 'bridge'
  nananana:
    name: 'nananana'
    internal: true

services:
  crypto:
    hostname: 'crypto'
    image: 'webmakom/crypto:0.0.2'
    restart: always
    ports:
      - "3305:3305" # http api
    network_mode: 'host'
    deploy:
      resources:
        limits:
          memory: 100mb

  cyclone:
    image: 'webmakom/cyclone:0.0.22'
    restart: always
    ports:
      - "3231:3231" # http api
      - "3203:3203/udp" # p2p
    environment:
      CYCLONE_LABEL: 'p1'
      CYCLONE_PEERS: '164.68.127.67:3203,164.68.127.58:3203'
      CYCLONE_PK: 'KwUjLXVF19uTjp5FnQrb4vmiEVQYgApdqAJDTUQ1T9C1wXirTTHS'
      CYCLONE_PUB: '020e119b3e3799afc17f7371c1a10a6fd38ced2d6662a1528d6675c8322de19234'
      CYCLONE_ADDR: '1Mxn3tAYPWogMqfD1geqiaqpAnjguPYAXF'
    network_mode: 'host'
    deploy:
      resources:
        limits:
          memory: 500mb

  vm:
    image: 'webmakom/vm:0.0.14'
    restart: always
    ports:
      - "8039:8039" # http api
    environment:
      VM_GENESIS_NATIVE: '1Mxn3tAYPWogMqfD1geqiaqpAnjguPYAXF:100000,1HSqakjKkwBR2YtXkxfUsfu2y7QEm1pDjN:100000,1L3cxnDxCYUuyzHgu9N4cexR7zeSEoLJvo:100000'
      VM_GENESIS_VALIDATORS: '1Mxn3tAYPWogMqfD1geqiaqpAnjguPYAXF,1HSqakjKkwBR2YtXkxfUsfu2y7QEm1pDjN,1L3cxnDxCYUuyzHgu9N4cexR7zeSEoLJvo'
    network_mode: 'host'
    deploy:
      resources:
        limits:
          memory: 500mb

  gw:
    image: 'webmakom/gw:0.0.10'
    restart: always
    ports:
      - "9231:9231" # http api
    network_mode: 'host'
    deploy:
      resources:
        limits:
          memory: 500mb

  storage:
    hostname: 'storage'
    image: 'webmakom/storage:0.0.3'
    ports:
      - '8801:8801'
      - '8802:8802'
    depends_on:
      - mongo-db
    networks:
      - boba
      - nananana
    deploy:
      resources:
        limits:
          memory: 500mb

  mongo-db:
    hostname: 'mongo-db'
    image: mongo:latest
    volumes:
      - /etc/cyclone-db:/data/db
    ports:
      - '27017:27017'
    networks:
      - nananana
    deploy:
      resources:
        limits:
          memory: 3000mb