version: '3.9'

networks:
  sai:
    name: 'sai'

services:
  cyclone:
    image: 'webmakom/cyclone:0.0.4'
    restart: always
    ports:
      - "3231:3231" # http api
      - "3203:3203" # p2p
    environment:
      CYCLONE_LABEL: 'p2'
      CYCLONE_PEERS: '164.68.127.226:3203,164.68.127.58:3203'
      CYCLONE_PK: 'KzwvwCC42X3BPa1wGQSsezQG9XWnUhLye9Fb9fAhYqzXiitmJMCm'
      CYCLONE_PUB: '0221c38bdecb94fea6729acc83b8aee37dd1bd6b43bffd92444e1e304e17605062'
      CYCLONE_ADDR: '1HSqakjKkwBR2YtXkxfUsfu2y7QEm1pDjN'
    depends_on:
      - storage
      - vm
      - crypto
    networks:
      - sai

  vm:
    image: 'webmakom/vm:0.0.4'
    restart: always
    ports:
      - "8039:8039" # http api
    depends_on:
      - storage
    networks:
      - sai

  gw:
    image: 'webmakom/gw:0.0.4'
    restart: always
    ports:
      - "9231:9231" # http api
    depends_on:
      - storage
      - crypto
    networks:
      - sai

  crypto:
    image: 'webmakom/crypto:0.0.1'
    restart: always
    ports:
      - "3305:3305" # http api
    networks:
      - sai

  storage:
    image: 'webmakom/storage:0.0.2'
    ports:
      - 8801:8801
      - 8802:8802
    depends_on:
      - mongo-db
    networks:
      - sai

  mongo-db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - sai
    ports:
      - 27018:27017

volumes:
  mongo_data: {}